
_plotmap = {
    # p.BASIC: basic,
    # p.LINE: line,
    # p.SPREAD: spread,
    # p.BAR: bar,
    # p.GROUPEDBAR: groupedbar,
    # p.STACKEDBAR: stackedbar,
    # p.HORIZONTALBAR: horizontalbar,
    # p.HORIZONTALSTACKEDBAR: horizontalstackedbar,
    # p.HISTOGRAM: histogram,
    # p.GROUPEDHIST: groupedhist,
    # p.STACKEDHIST: stackedhist,
    # p.BOX: box,
    # p.PIE: pie,
    # p.AREA: area,
    # p.STACKEDAREA: stackedarea,
    # p.FILLEDAREA: filledarea,
    # p.SCATTER: scatter,
    # p.BUBBLE: bubble,
    # p.SCATTERMATRIX: scattermatrix,
    # p.HEATMAP: heatmap,
    # p.MULTISCATTER: multiscatter,
    # p.GROUPEDSCATTER: groupedscatter,
    # p.OHLC: ohlcv,
    # p.OHLVC: ohlcv,
    # p.CANDLESTICK: candlestick
}